sudo: false

language: node_js

node_js:
    - '10'

branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
    directories:
        - node_modules

services:
    - xvfb

addons:
    chrome: stable

install:
    - npm set progress=false
    - npm install
    - npm install coveralls

script:
    - npm test
    - cat ./coverage/observables/lcov.info | ./node_modules/coveralls/bin/coveralls.js
